In [12]:
import pandas as pd
import numpy as np

In [13]:
data = pd.read_excel ("Volumetric_features.xlsx")

In [14]:
data.head()

S.No  Left-Lateral-Ventricle  Left-Inf-Lat-Vent  \
0     1                 22916.9              982.7   
1     2                 22953.2              984.5   
2     3                 23320.4             1062.1   
3     4                 24360.0             1000.5   
4     5                 25769.4             1124.4   

   Left-Cerebellum-White-Matter  Left-Cerebellum-Cortex  Left-Thalamus  \
0                       15196.7                 55796.4         6855.5   
1                       15289.7                 55778.6         6835.1   
2                       15382.1                 55551.2         7566.0   
3                       14805.4                 54041.8         8004.6   
4                       16331.1                 54108.6         6677.4   

   Left-Caudate  Left-Putamen  Left-Pallidum  3rd-Ventricle  ...  \
0        2956.4        4240.7         2223.9         2034.4  ...   
1        3064.2        4498.6         2354.1         1927.1  ...   
2        3231.7        4456.2         1995.4         2064.7  ...   
3        3137.3        4262.2         1983.4         2017.7  ...   
4        2964.4        4204.6         2409.7         2251.8  ...   

   rh_supramarginal_thickness  rh_frontalpole_thickness  \
0                       2.408                     2.629   
1                       2.417                     2.640   
2                       2.374                     2.601   
3                       2.366                     2.639   
4                       2.381                     2.555   

   rh_temporalpole_thickness  rh_transversetemporal_thickness  \
0                      3.519                            2.009   
1                      3.488                            2.111   
2                      3.342                            2.146   
3                      3.361                            2.056   
4                      3.450                            2.052   

   rh_insula_thickness  rh_MeanThickness_thickness  BrainSegVolNotVent.2  \
0                2.825                     2.33635               1093846   
1                2.720                     2.34202               1099876   
2                2.684                     2.31982               1097999   
3                2.700                     2.29215               1070117   
4                2.574                     2.30397               1075926   

        eTIV.1  Age  dataset  
0  1619602.965   85        1  
1  1624755.130   85        1  
2  1622609.518   86        1  
3  1583854.236   87        1  
4  1617375.362   89        1  

[5 rows x 141 columns]

In [15]:
#matrix of features
X = data.iloc[:,1:138].values
#vectors of age  
Y = data.iloc[:,139].values

In [16]:
#splitting dataset into training and testing dataset
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=0) #test size is 20% of the data, remaining 80 is training

In [17]:
#feature scaling to convert all variables to the same scale
from sklearn.preprocessing import StandardScaler
scaler =StandardScaler()
scaler

StandardScaler()

In [18]:
X_train = scaler.fit_transform(X_train)
X_train

array([[ 0.54136603, -0.1368328 ,  0.31845673, ..., -0.46094787,
        -0.76319662,  1.00380988],
       [ 0.68175873,  1.67742788, -1.1352392 , ..., -0.83558521,
        -0.88668081, -0.94096758],
       [ 0.08362916,  0.25506118,  1.03104094, ...,  0.05225397,
         0.4721229 ,  1.0276959 ],
       ...,
       [-0.37374801, -0.44467627, -0.00934558, ...,  1.63804765,
         0.53038561, -0.1824054 ],
       [-0.4928747 , -0.39872184,  0.44732112, ..., -0.32238337,
         0.13571375,  1.37107146],
       [-0.30653828, -0.45253465, -0.90584927, ...,  0.73994443,
        -0.25138533,  0.0837151 ]])

In [19]:
X_train.mean(axis=0) #standardized data should have mean of 0

array([-1.50702922e-15,  4.30309963e-16,  1.40810440e-14,  9.61933524e-15,
        4.91318032e-15, -8.68486742e-16,  2.49306164e-14, -1.13093952e-14,
        4.46060020e-16,  1.02124095e-15,  2.01997853e-14,  7.75640236e-15,
        5.69876165e-15, -2.99903100e-15,  7.62512998e-15,  8.32512888e-15,
        1.46349074e-16,  4.08250028e-15,  1.92107999e-15, -1.39354340e-15,
        1.08936528e-15, -2.08635706e-14, -1.37530109e-14,  1.47622217e-14,
        1.25928196e-15,  1.23504100e-17, -2.96183422e-14,  1.50445074e-15,
       -3.13460632e-15, -3.75350638e-15,  1.47843605e-15, -3.74230561e-15,
       -1.15725969e-15, -5.15646040e-16,  0.00000000e+00,  0.00000000e+00,
        2.58385522e-16,  0.00000000e+00,  0.00000000e+00, -9.81627665e-16,
       -2.16746410e-15, -7.70967774e-15,  2.14062824e-15, -5.95084468e-15,
        4.33795012e-15,  5.02958950e-16,  7.60194833e-16,  7.67275789e-15,
       -9.44321873e-15, -5.02213327e-15, -2.57083966e-16,  1.61015185e-16,
       -4.86790095e-17, -

In [20]:
X_train.std(axis=0) #standardized data should have a unit variance

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       0., 0., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1.])

In [21]:
X_test = scaler.transform(X_test) #use transform on test set so the same mean and variance 
                                  #used on the training data as is used to transform our test data

In [22]:
from sklearn.tree import DecisionTreeRegressor
regr = DecisionTreeRegressor()
regr.fit(X_train, Y_train)

DecisionTreeRegressor()

In [23]:
regr.predict(X_train)

array([76., 67., 58., ..., 40., 67., 54.])

In [24]:
Y_predict_train=regr.predict(X_train)

In [25]:
from sklearn import metrics
VAR = metrics.explained_variance_score(Y_train, Y_predict_train)
MAE = metrics.mean_absolute_error(Y_train, Y_predict_train)
MSE = metrics.mean_squared_error(Y_train, Y_predict_train)
RMSE = np.sqrt(metrics.mean_squared_error(Y_train, Y_predict_train))

print('Explained Variance:', VAR)
print('Mean Absolute Error:', MAE)
print('Mean Square Error:', MSE)
print('Root Mean Square Error:', RMSE)

Explained Variance: 1.0
Mean Absolute Error: 0.0
Mean Square Error: 0.0
Root Mean Square Error: 0.0


In [26]:
regr.fit(X_test, Y_test)

DecisionTreeRegressor()

In [27]:
Y_predict_test=regr.predict(X_test)

In [28]:
from sklearn import metrics
VAR = metrics.explained_variance_score(Y_test, Y_predict_test)
MAE = metrics.mean_absolute_error(Y_test, Y_predict_test)
MSE = metrics.mean_squared_error(Y_test, Y_predict_test)
RMSE = np.sqrt(metrics.mean_squared_error(Y_test, Y_predict_test))

print('Explained Variance:', VAR)
print('Mean Absolute Error:', MAE)
print('Mean Square Error:', MSE)
print('Root Mean Square Error:', RMSE)

Explained Variance: 1.0
Mean Absolute Error: 0.0
Mean Square Error: 0.0
Root Mean Square Error: 0.0


(4226, 137)

(4226,)