In [2]:
import numpy as np
import pandas as pd

In [3]:
data = pd.read_csv("breast-cancer.csv")

In [4]:
data.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  radius_worst  texture_worst  perimeter_worst  area_worst  \
0  ...         25.38          17.33           184.60      2019.0   
1  ...         24.99          23.41           158.80      1956.0   
2  ...         23.57          25.53           152.50      1709.0   
3  ...         14.91          26.50            98.87       567.7   
4  ...         22.54          16.67           152.20      1575.0   

   smoothness_worst  compactness_worst  concavity_worst  concave points_worst  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   symmetry_worst  fractal_dimension_worst  
0          0.4601                  0.11890  
1          0.2750                  0.08902  
2          0.3613                  0.08758  
3          0.6638                  0.17300  
4          0.2364                  0.07678  

[5 rows x 32 columns]

In [5]:
#matrix of 30 features
X = data.iloc[:,2:19].values

In [6]:
#vectors of diagnosis 
Y = data.iloc[:,1].values
#Y=Y.astype('int')

In [7]:
#encoding categorical variable - diagnosis - M (malignant) or B (benign) 
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit(Y)

LabelEncoder()

In [8]:
#splitting dataset into training and testing dataset
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=0) #test size is 20% of the data, remaining 80 is training

In [9]:
#feature scaling to convert all variables to the same scale
from sklearn import preprocessing
scaler = preprocessing.StandardScaler().fit(X_train)
scaler

StandardScaler()

In [10]:
scaler.mean_

array([1.41124989e+01, 1.91528791e+01, 9.18182857e+01, 6.53819121e+02,
       9.64133407e-02, 1.03318659e-01, 8.74845356e-02, 4.86900264e-02,
       1.80939121e-01, 6.26680220e-02, 4.02523516e-01, 1.20988066e+00,
       2.82524681e+00, 4.02856176e+01, 7.00339341e-03, 2.50632286e-02,
       3.14727859e-02])

In [11]:
scaler.scale_

array([3.53148742e+00, 4.15439017e+00, 2.42862794e+01, 3.57772373e+02,
       1.37841928e-02, 5.04344575e-02, 7.77159693e-02, 3.85550295e-02,
       2.73677762e-02, 6.81132951e-03, 2.84057900e-01, 5.41365325e-01,
       2.03551332e+00, 4.76779413e+01, 2.84053720e-03, 1.74905171e-02,
       3.10715741e-02])

In [12]:
X_train = scaler.transform(X_train)
X_train

array([[-1.15036482, -0.39064196, -1.12855021, ...,  0.28149837,
        -0.60451206, -0.46900701],
       [-0.93798972,  0.68051405, -0.94820146, ..., -0.1620797 ,
        -0.20486693, -0.05029632],
       [ 0.574121  , -1.03333557,  0.51394098, ..., -1.07211882,
        -0.72057496, -0.42362791],
       ...,
       [-1.32422924, -0.20048168, -1.31754581, ..., -0.05893019,
        -0.91942557, -0.25723788],
       [-1.24380987, -0.2245526 , -1.28007609, ..., -1.86246228,
        -1.04783801, -1.0129125 ],
       [-0.73694129,  1.14989702, -0.71226578, ...,  0.42126067,
         0.27196288,  0.83379149]])

In [13]:
scaler.mean_

array([1.41124989e+01, 1.91528791e+01, 9.18182857e+01, 6.53819121e+02,
       9.64133407e-02, 1.03318659e-01, 8.74845356e-02, 4.86900264e-02,
       1.80939121e-01, 6.26680220e-02, 4.02523516e-01, 1.20988066e+00,
       2.82524681e+00, 4.02856176e+01, 7.00339341e-03, 2.50632286e-02,
       3.14727859e-02])

In [14]:
X_train.mean(axis=0) #standardized data should have a mean of 0 ,

array([-8.80126253e-16, -3.35165351e-15,  3.23355506e-15, -2.22727819e-15,
       -1.45829624e-15,  5.12219998e-16,  6.77114042e-16,  4.87766116e-16,
       -5.69068602e-15,  6.63571762e-16,  5.29490981e-17,  6.00252448e-16,
        8.27299157e-16,  1.82881793e-16,  1.82381582e-15,  2.39490967e-16,
        3.15742548e-16])

In [15]:
X_train.std(axis=0) #standardized data should have a unit variance

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [16]:
from sklearn.neural_network import MLPClassifier
clf = MLPClassifier(solver='adam', alpha=1e-5, hidden_layer_sizes=(5, 2),  max_iter=5000, random_state=1)
clf.fit(X_train, Y_train)

MLPClassifier(alpha=1e-05, hidden_layer_sizes=(5, 2), max_iter=5000,
              random_state=1)

In [17]:
clf.predict(X_train)

array(['B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'M', 'B', 'B',
       'B', 'B', 'B', 'M', 'B', 'B', 'M', 'B', 'B', 'B', 'M', 'M', 'B',
       'B', 'B', 'M', 'B', 'B', 'M', 'B', 'M', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'M', 'B', 'M', 'B', 'M', 'M', 'B', 'B', 'M', 'B', 'M',
       'M', 'M', 'B', 'B', 'B', 'B', 'B', 'B', 'M', 'B', 'B', 'B', 'B',
       'M', 'M', 'B', 'B', 'M', 'B', 'B', 'B', 'B', 'M', 'B', 'B', 'M',
       'M', 'B', 'B', 'M', 'M', 'B', 'B', 'M', 'B', 'B', 'M', 'M', 'M',
       'B', 'B', 'B', 'M', 'B', 'B', 'B', 'B', 'B', 'M', 'B', 'M', 'B',
       'M', 'B', 'M', 'B', 'B', 'B', 'B', 'B', 'B', 'M', 'B', 'M', 'B',
       'B', 'B', 'M', 'B', 'B', 'B', 'M', 'B', 'B', 'M', 'M', 'B', 'M',
       'B', 'M', 'B', 'M', 'M', 'M', 'M', 'B', 'B', 'B', 'M', 'B', 'M',
       'B', 'M', 'B', 'B', 'M', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'M', 'B', 'B', 'B', 'M', 'B', 'B', 'B',
       'B', 'B', 'B', 'M', 'B', 'M', 'B', 'B', 'M', 'B', 'M', 'M

In [18]:
Y_predict_train=clf.predict(X_train)

In [19]:
from sklearn.metrics import classification_report
print(classification_report(Y_train, Y_predict_train))

              precision    recall  f1-score   support

           B       0.97      1.00      0.98       290
           M       0.99      0.95      0.97       165

    accuracy                           0.98       455
   macro avg       0.98      0.97      0.98       455
weighted avg       0.98      0.98      0.98       455



In [20]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(Y_train, Y_predict_train))

[[289   1]
 [  8 157]]


In [21]:
clf = MLPClassifier(solver='adam', alpha=1e-5, hidden_layer_sizes=(5, 2),  max_iter=5000, random_state=1)
clf.fit(X_test, Y_test)

MLPClassifier(alpha=1e-05, hidden_layer_sizes=(5, 2), max_iter=5000,
              random_state=1)

In [22]:
Y_predict_test=clf.predict(X_test)

In [23]:
print(classification_report(Y_test, Y_predict_test)) # , labels=np.unique(Y_predict_test), zero_division=0

              precision    recall  f1-score   support

           B       0.00      0.00      0.00        67
           M       0.41      1.00      0.58        47

    accuracy                           0.41       114
   macro avg       0.21      0.50      0.29       114
weighted avg       0.17      0.41      0.24       114



/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [30]:
Y_test

array(['M', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'M', 'B', 'M', 'M', 'M', 'M', 'M', 'B', 'B', 'M', 'B',
       'B', 'M', 'B', 'M', 'B', 'M', 'B', 'M', 'B', 'M', 'B', 'M', 'B',
       'M', 'M', 'B', 'M', 'B', 'B', 'M', 'B', 'B', 'B', 'M', 'M', 'M',
       'M', 'B', 'B', 'B', 'B', 'B', 'B', 'M', 'M', 'M', 'B', 'B', 'M',
       'B', 'M', 'M', 'M', 'B', 'B', 'M', 'B', 'M', 'M', 'B', 'B', 'B',
       'B', 'B', 'M', 'M', 'M', 'B', 'M', 'B', 'B', 'B', 'M', 'M', 'B',
       'M', 'B', 'M', 'B', 'B', 'M', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'M', 'B', 'M', 'B', 'M', 'M', 'B', 'M', 'M', 'B'], dtype=object)

In [31]:
Y_predict_test

array(['M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M'], dtype='<U1')